# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b99e6f8b57049ef33eb24922b88e9b684bcded555b3f5204d4e8b80df864337a70f55c5d11a4de9ae8f9d2e80b18dd4c63387eb1127a7814cc316f2e7c0d87e1

test:
  secret_key_base: 2a2b781d9f6170bff78cd66c3b639152f0ebcab24981698c73529c088f0c5fc9ed6bf1107fd3fe936e2b1939965b4433d54e6771e251b3ab9cc7f4d430fbdad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
